![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np
print(np.__version__)

2.2.0


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [3]:
my_array = np.arange(0,10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [35]:
#METODO 1

a = np.arange(0,9).reshape(3, 3)
print(a)

for x in range(a.shape[0]):
    for i in range(a.shape[1]):
        a[x][i] = True

print(a)
        
#METODO 2

b = np.full((3,3), True)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [56]:
#METODO 1
arrrrrray = []
for x in my_array:
    if x%2!=0:
        arrrrrray.append(x)
print(arrrrrray)

#METODO 2
mask = my_array %2 !=0
print(my_array[mask])


[np.int64(1), np.int64(3), np.int64(5), np.int64(7), np.int64(9)]
[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [55]:
new_array = my_array.copy()
mask = new_array %2 !=0
new_array[mask]=-1

print(new_array)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [59]:
ejer_6 = my_array.copy()
print(np.where(ejer_6 %2 !=0, -1, ejer_6))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [65]:
print(my_array)
ejer_7 = my_array.reshape((2,5))
print(ejer_7)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [40]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [41]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [44]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )

    Join a sequence of arrays along an existing axis.

    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.20.0

    c

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [49]:
my_array = np.arange(0,10)
print(my_array)

print(my_array[0])
print(my_array[-1])
print(my_array[1:8])

[0 1 2 3 4 5 6 7 8 9]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [ ]:
my_matrix = np.array[[1,2,3],
                     [4,5,6],
                     [7,8,9]]

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [50]:
ejer_14 = np.arange(1,50)
print(ejer_14[::3])

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [66]:
print(np.random.randint(0,100, size = (5,3,4)))

[[[37 56 63 36]
  [97 19 84 66]
  [73 21 60 32]]

 [[17 72 29 87]
  [ 9 57 13 42]
  [99 98 29 61]]

 [[24 24 87 43]
  [ 6 85 58 14]
  [ 3 97 35  1]]

 [[94 53  3 65]
  [24 65 90 97]
  [72 46 38 28]]

 [[20 44 15 76]
  [24 73  8  0]
  [62 85 82 12]]]


## Ejercicio 16
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [72]:
ejer_16 = np.full((10,1), True)
print(ejer_16)
print()
ejer_16_1 = ejer_16.reshape((2,5))
print(ejer_16_1)

[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]

[[ True  True  True  True  True]
 [ True  True  True  True  True]]


## Ejercicio 17
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [78]:
x = np.random.randint(10, 20, size = (5,2,6))
print(x)
print()

print("Número de elementos:", x.size)

print("Número de dimensiones:", x.ndim)

print("Longitud de cada dimensión:", x.shape)

print("Tamaño de un elemento:", x.itemsize)

[[[19 16 15 17 10 15]
  [11 18 15 18 17 13]]

 [[17 10 18 11 15 10]
  [14 18 13 13 18 18]]

 [[12 19 15 14 16 15]
  [14 18 10 19 12 18]]

 [[14 10 10 11 16 19]
  [19 16 10 19 12 17]]

 [[10 16 10 16 12 15]
  [18 19 10 10 16 18]]]

Número de elementos: 60
Número de dimensiones: 3
Longitud de cada dimensión: (5, 2, 6)
Tamaño de un elemento: 4
