![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [86]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [87]:
print(my_array[::-2])

[9 7 5 3 1]


In [88]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [89]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [90]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [91]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [92]:
print(my_array[2::-1])

[2 1 0]


In [93]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [94]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [95]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [96]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [97]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [98]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [99]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [100]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [101]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [102]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [103]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [104]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [105]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [106]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [107]:
x == "Loro"

array([ True, False, False,  True, False])

In [108]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [109]:
print(np.where(x== "Loro")[0])

[0 3]


In [110]:
print(np.where(x == "Loro")[0])

[0 3]


In [111]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [112]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [113]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [114]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [115]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [6]:
ejer_10 = np.zeros(10)
print(ejer_10)

ejer_10[4] = 1
print(ejer_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [8]:
ejer_11 = np.arange(10,50)
print(ejer_11)
print()
print(ejer_11[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [ ]:
def erase_num(v):
    mask = v != 0
    return mask

v = np.array([1,2,0,0,4,0])

print(v[erase_num(v)])

[1 2 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [87]:
ejer_13 = np.random.randint(0, 100, size = (10,10))
print(ejer_13)
print()
print(np.max(ejer_13))
print(np.min(ejer_13))

[[37 67 18 71 87 29 83 46 70 89]
 [34 14 83  2 86 91 18  2 25 46]
 [47 18 12 46 88  2 56 61  4 35]
 [ 5 18 93 82 84 61 57 76 55 76]
 [22 41 83  3 68  1  3 29 56 55]
 [64 82 58 33 36 63 50  8 89 41]
 [68 45 67 46 91 75 82 54 17 18]
 [79 24 26 22 65 38 62 91 41  6]
 [24 11 58 60 49  1 87 51 58 43]
 [90 84  7 79 77 97 59 75 65  1]]

97
1


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [98]:
ejer_14 = np.random.randint(0,10, size = (30))
print(ejer_14)
print()
print(np.mean(ejer_14))

[9 6 1 3 2 9 4 3 2 7 3 2 6 5 5 7 6 6 3 2 7 4 3 7 3 3 6 7 9 3]

4.766666666666667


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
ejer_15 = np.random.randint(0,10, size = (5,5))
print(ejer_15)
print()
print((ejer_15-np.mean(ejer_15))/np.std(ejer_15))

[[2 0 0 3 9]
 [5 0 7 7 0]
 [2 6 7 4 6]
 [3 5 8 5 5]
 [6 1 3 9 1]]

[[-0.761092   -1.46580681 -1.46580681 -0.40873459  1.70540984]
 [ 0.29598022 -1.46580681  1.00069503  1.00069503 -1.46580681]
 [-0.761092    0.64833763  1.00069503 -0.05637718  0.64833763]
 [-0.40873459  0.29598022  1.35305244  0.29598022  0.29598022]
 [ 0.64833763 -1.1134494  -0.40873459  1.70540984 -1.1134494 ]]


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [119]:
ejer_16 = np.arange(0,11)
print(ejer_16)
print()
# ejer_16_1 = ejer_16[3:9].copy()
print(ejer_16)
ejer_16[3:9]=-1
print(ejer_16)
ejer_16_1 = ejer_16.copy()
print(ejer_16_1[3:9]*-1)

[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[1 1 1 1 1 1]
